embold scan with quality gate

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -30,5 +30,11 @@ jobs:
         env:
           EMBOLD_URL: https://oss.emboldci.dev
           EMBOLD_TOKEN: ${{ secrets.EMBOLD_OSS_SCAN_TOKEN }}
-        run: mvn -B package io.embold.scan:embold-maven-plugin:embold -Dembold.host.url=https://oss.emboldci.dev -Dembold.user.token=${{ secrets.EMBOLD_OSS_SCAN_TOKEN }} --file pom.xml
-
+        run: |
+          mvn -B package io.embold.scan:embold-maven-plugin:embold -Dembold.host.url=https://oss.emboldci.dev -Dembold.user.token=${{ secrets.EMBOLD_OSS_SCAN_TOKEN }} --file pom.xml
+          response=$(curl --silent --location --request GET "https://oss.emboldci.dev/api/v1/repositories/2dd6b50efbd23318bd3505d5029e1318/qualitygateprofiles/status" --header "Authorization:Bearer ${{ secrets.EMBOLD_OSS_SCAN_TOKEN }}")
+          if [ "$response" != 'passed' ]; then
+            echo "Quality gate failed"
+            exit 1
+          fi
+          echo "Quality gate passed"
